# Generated by Django 4.2.4 on 2023-09-04 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=200)),
                ('sales', models.DecimalField(decimal_places=2, max_digits=8)),
                ('maxTemp', models.DecimalField(decimal_places=2, max_digits=5)),
                ('minTemp', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
