# Generated by Django 4.2.4 on 2023-09-04 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='date',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='maxTemp',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='minTemp',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='sales',
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales', models.DecimalField(decimal_places=2, max_digits=8)),
                ('maxTemp', models.DecimalField(decimal_places=2, max_digits=5)),
                ('minTemp', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date', models.DateTimeField()),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.shop')),
            ],
        ),
    ]
