# Generated by Django 4.2.4 on 2023-09-04 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_shop_date_remove_shop_maxtemp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='lat',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='lon',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
    ]
