# Generated by Django 4.2.4 on 2023-09-04 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_shop_lat_shop_lon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='lon',
            new_name='lng',
        ),
    ]
