# Generated by Django 4.2.4 on 2023-09-05 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_lon_shop_lng'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='lat',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True, verbose_name='緯度'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='lng',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True, verbose_name='経度'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='location',
            field=models.CharField(max_length=200, verbose_name='地域'),
        ),
    ]
