# Generated by Django 4.2.4 on 2023-09-08 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_shop_lat_alter_shop_lng_alter_shop_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.shop'),
        ),
    ]
