# Generated by Django 4.2.4 on 2023-09-08 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_data_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='humid',
            field=models.DecimalField(decimal_places=2, default=65, max_digits=5, verbose_name='湿度'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='data',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.shop', verbose_name='地域'),
        ),
        migrations.AlterField(
            model_name='data',
            name='maxTemp',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='最高気温'),
        ),
        migrations.AlterField(
            model_name='data',
            name='minTemp',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='最低気温'),
        ),
        migrations.AlterField(
            model_name='data',
            name='sales',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='売り上げ'),
        ),
    ]
