# Generated by Django 4.2.4 on 2023-09-08 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_data_humid_alter_data_location_alter_data_maxtemp_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='maxTemp',
            new_name='Temp',
        ),
        migrations.RemoveField(
            model_name='data',
            name='minTemp',
        ),
    ]
